### ISSUE TITLE
Model persister ignores AssertionError

### ISSUE THREAD

**Issue by ottonemo** [ottogroup/palladium#88]
When using a model persister (does not seem to matter whether it is `palladium.persistence.CachedUpdatePersister` or `palladium.persistence.File`), starting a service where model loading throws an exception swallows the underlying error and simply reports a `KeyError: model`:

```
ERROR:palladium:Unexpected error
Traceback (most recent call last):
  File "/opt/conda/envs/blotto/lib/python3.6/site-packages/palladium/server.py", line 201, in predict
    model = model_persister.read()
  File "/opt/conda/envs/blotto/lib/python3.6/site-packages/palladium/persistence.py", line 484, in read
    return self.cache[self.key]
  File "/opt/conda/envs/blotto/lib/python3.6/site-packages/palladium/util.py", line 214, in __getitem__
    return super(ProcessStore, self).__getitem__(key)
  File "/opt/conda/envs/blotto/lib/python3.6/collections/__init__.py", line 993, in __getitem__
    raise KeyError(key)
KeyError: 'model'
```

However if I run `get_config` manually I will get the underlying error:

```python
>>> from palladium.util import get_config
>>> c = get_config()
DEBUG:gensim.models.doc2vec:Fast version of gensim.models.doc2vec is being used
INFO:summa.preprocessing.cleaner:'pattern' package not found; tag filters are not available for English
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/blotto/lib/python3.6/site-packages/palladium/util.py", line 91, in get_config
    _initialize_config(_config)
  File "/opt/conda/envs/blotto/lib/python3.6/site-packages/palladium/util.py", line 136, in _initialize_config
    component.initialize_component(config)
  File "/opt/conda/envs/blotto/lib/python3.6/site-packages/palladium/persistence.py", line 473, in initialize_component
    self.update_cache()
  File "/opt/conda/envs/blotto/lib/python3.6/site-packages/palladium/util.py", line 365, in wrapper
    return self.wrapped(*args, **kwargs)
  File "/opt/conda/envs/blotto/lib/python3.6/site-packages/palladium/persistence.py", line 490, in update_cache
    model = self.impl.read(*args, **kwargs)
  File "/opt/conda/envs/blotto/lib/python3.6/site-packages/palladium/persistence.py", line 94, in read
    return pickle.load(f)
  File "/opt/conda/envs/blotto/lib/python3.6/site-packages/torch/cuda/__init__.py", line 492, in _lazy_new
    _lazy_init()
  File "/opt/conda/envs/blotto/lib/python3.6/site-packages/torch/cuda/__init__.py", line 160, in _lazy_init
    _check_driver()
  File "/opt/conda/envs/blotto/lib/python3.6/site-packages/torch/cuda/__init__.py", line 74, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

**Comment by dnouri** [comment]
Which version of Paladium is this? I had trouble reproducing this behaviour with both 1.0.1.1 and the latest development version.

**Comment by dnouri** [comment]
@ottonemo Also is this using pld-devserver or another WSGI server?

**Comment by dnouri** [comment]
I believe the problem is that you're using a custom `wsgi.py` module that doesn't call `initialize_config()`.  Thus, `initialize_config()` will be called when the first request is made.

The solution would be to instead use Palladium's own `palladium.wsgi` module.  A `gunicorn` call could look like this:

```
gunicorn -b 0.0.0.0:5001 palladium.wsgi:app
```

The effect is that if now something is wrong during initialization, gunicorn will exit and you will see the error.

**Comment by dnouri** [comment]
@ottonemo I'll assume that this fixed your problem.
